export interface GT7Data {
    magic: number;
    position: [number, number, number];
    velocity: [number, number, number];
    rotation: [number, number, number];
    relativeOrientationToNorth: number;
    angularVelocity: [number, number, number];
    bodyHeight: number;
    engineRPM: number;
    gasLevel: number;
    gasCapacity: number;
    metersPerSecond: number;
    turboBoost: number;
    oilPressure: number;
    waterTemperature: number;
    oilTemperature: number;
    tireFrontLeftSurfaceTemperature: number;
    tireFrontRightSurfaceTemperature: number;
    tireRearLeftSurfaceTemperature: number;
    tireRearRightSurfaceTemperature: number;
    packetId: number;
    lapCount: number;
    lapsInRace: number;
    bestLapTime: number;
    lastLapTime: number;
    timeOfDayProgression: number;
    preRaceStartPositionOrQualiPos: number;
    numCarsAtPreRace: number;
    minAlertRPM: number;
    maxAlertRPM: number;
    calculatedMaxSpeed: number;
    flags: number;
    currentGear: number;
    suggestedGear: number;
    throttle: number;
    brake: number;
    roadPlane: [number, number, number];
    roadPlaneDistance: number;
    wheelFrontLeftRevPerSecond: number;
    wheelFrontRightRevPerSecond: number;
    wheelRearLeftRevPerSecond: number;
    wheelRearRightRevPerSecond: number;
    tireFrontLeftTireRadius: number;
    tireFrontRightTireRadius: number;
    tireRearLeftTireRadius: number;
    tireRearRightTireRadius: number;
    tireFrontLeftSusHeight: number;
    tireFrontRightSusHeight: number;
    tireRearLeftSusHeight: number;
    tireRearRightSusHeight: number;
    clutchPedal: number;
    clutchEngagement: number;
    rpmFromClutchToGearbox: number;
    transmissionTopSpeed: number;
    gearRatios: [number, number, number, number, number, number, number, number];
    carCode: number;
}
