import { Parser } from 'binary-parser';

export const gt7parser = new Parser()
    .endianness('little')
    .int32le('magic', { assert: 0x47375330 })
    .array('position', { type: 'floatle', length: 3 })
    .array('velocity', { type: 'floatle', length: 3 })
    .array('rotation', { type: 'floatle', length: 3 })
    .floatle('relativeOrientationToNorth')
    .array('angularVelocity', { type: 'floatle', length: 3 })
    .floatle('bodyHeight')
    .floatle('engineRPM')
    .skip(4)
    .floatle('gasLevel')
    .floatle('gasCapacity')
    .floatle('metersPerSecond')
    .floatle('turboBoost')
    .floatle('oilPressure')
    .floatle('waterTemperature')
    .floatle('oilTemperature')
    .floatle('tireFrontLeftSurfaceTemperature')
    .floatle('tireFrontRightSurfaceTemperature')
    .floatle('tireRearLeftSurfaceTemperature')
    .floatle('tireRearRightSurfaceTemperature')
    .int32le('packetId')
    .int16le('lapCount')
    .int16le('lapsInRace')
    .int32le('bestLapTime')
    .int32le('lastLapTime')
    .int32le('timeOfDayProgression')
    .int16le('preRaceStartPositionOrQualiPos')
    .int16le('numCarsAtPreRace')
    .int16le('minAlertRPM')
    .int16le('maxAlertRPM')
    .int16le('calculatedMaxSpeed')
    .int16le('flags')
    .bit4('currentGear')
    .bit4('suggestedGear')
    .uint8('throttle')
    .uint8('brake')
    .skip(1)
    .array('roadPlane', { type: 'floatle', length: 3 })
    .floatle('roadPlaneDistance')
    .floatle('wheelFrontLeftRevPerSecond')
    .floatle('wheelFrontRightRevPerSecond')
    .floatle('wheelRearLeftRevPerSecond')
    .floatle('wheelRearRightRevPerSecond')
    .floatle('tireFrontLeftTireRadius')
    .floatle('tireFrontRightTireRadius')
    .floatle('tireRearLeftTireRadius')
    .floatle('tireRearRightTireRadius')
    .floatle('tireFrontLeftSusHeight')
    .floatle('tireFrontRightSusHeight')
    .floatle('tireRearLeftSusHeight')
    .floatle('tireRearRightSusHeight')
    .skip(32)
    .floatle('clutchPedal')
    .floatle('clutchEngagement')
    .floatle('rpmFromClutchToGearbox')
    .floatle('transmissionTopSpeed')
    .array('gearRatios', { type: 'floatle', length: 8 })
    .int32le('carCode');
